---
driver:
  name: docker
driver_config:
  require_chef_omnibus: true
  use_sudo: false
  links: elasticsearch:elasticsearch

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

dns:
  - 8.8.8.8
  - 8.8.4.4

suites:
  - name: default
    run_list: ['ucnext_test::default']
