name 'ucnext'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures ucnext'
long_description 'Installs/Configures ucnext'
version '0.3.10'
